### ISSUE TITLE
Nest data stopped coming in with splunkd error

### ISSUE THREAD

**Issue by baldwintm** [ryanwoconnor/NestAddonforSplunk#2]
Nest data stopped coming in.
Here is splunkd.log error:

 Process Process-1:
 Traceback (most recent call last):
   File "/opt/splunk/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
     self.run()
   File "/opt/splunk/lib/python2.7/multiprocessing/process.py", line 114, in run
     self._target(_self._args, *_self._kwargs)
   File "/opt/splunk/etc/apps/NestAddonForSplunk/bin/devices.py", line 60, in get_devices
     return true
 NameError: global name 'true' is not defined

**Comment by baldwintm** [comment]
This issue has been fixed by the latest commit
